#!/bin/bash -eu

if [ $# -ne 1 ]; then
  echo "Usage: ./deploy VERSION_MANIFEST_JSON_STRING"
  exit 1
fi

policy_version=$(jq -r '.ida_hub_version' <<< "$1")
if [[ "$policy_version" == "null" ]]; then
  echo "No ida_hub_version entry in ${1}"
  exit 1
fi
verify_policy_app_config_version=$(jq -r '.verify_policy_app_config_version' <<< "$1")
if [[ "$verify_policy_app_config_version" == "null" ]]; then
  echo "No verify_policy_app_config_version entry in ${1}"
  exit 1
fi

/usr/bin/apt-get -qq update

for PACKAGE in verify-policy-app-config policy; do
  VERSION_VAR=${PACKAGE//-/_}_version
  VERSION_SPECIFIED=${!VERSION_VAR}

  /usr/bin/apt-get install \
    -qfy --reinstall --force-yes \
    -o DPkg::Options::=--force-confnew \
    $PACKAGE="$VERSION_SPECIFIED"
done
