#!/bin/bash -eu

if [ $# -ne 1 ]; then
  echo "Usage: ./deploy VERSION_MANIFEST_JSON_STRING"
  exit 1
fi

saml_soap_proxy_version=$(echo $1 | jq -r '.ida_hub_version')
if [[ "$saml_soap_proxy_version" == "null" ]]; then
  echo "No ida_hub_version entry in ${1}"
  exit 1
fi
verify_saml_soap_proxy_app_config_version=$(echo $1 | jq -r '.verify_saml_soap_proxy_app_config_version')
if [[ "$verify_saml_soap_proxy_app_config_version" == "null" ]]; then
  echo "No verify_saml_soap_proxy_app_config_version entry in ${1}"
  exit 1
fi

/usr/bin/apt-get -qq update

for PACKAGE in verify-saml-soap-proxy-app-config saml-soap-proxy; do
  VERSION_VAR=${PACKAGE//-/_}_version
  VERSION_SPECIFIED=${!VERSION_VAR}

  /usr/bin/apt-get install \
    -qfy --reinstall --force-yes \
    -o DPkg::Options::=--force-confnew \
    $PACKAGE="$VERSION_SPECIFIED"
done
