#!/bin/bash -eu

if [ $# -ne 1 ]; then
  echo "Usage: ./deploy VERSION_MANIFEST_JSON_STRING"
  exit 1
fi

saml_soap_proxy_version=$(echo $1 | jq -r '.ida_hub_version')
if [[ "$saml_soap_proxy_version" == "null" ]]; then
  echo "No ida_hub_version entry in ${1}"
  exit 1
fi

/usr/bin/apt-get -qq update

/usr/bin/apt-get install \
  -qfy --reinstall --force-yes \
  -o DPkg::Options::=--force-confnew \
  saml-soap-proxy="$saml_soap_proxy_version"
